kind: Service
apiVersion: v1
metadata:
  name: apiapp
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiapp
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "api"
        dapr.io/app-port: "80"
    spec:
      containers:
      - name: api
        image: kostapetanregistry.azurecr.io/hello-kubernetes/api:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
