apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisherapp
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
    spec:
      containers:
      - name: publisher
        image: kostapetanregistry.azurecr.io/pubsub/publisher:v1
